[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/contact-dj-misha/"
  to = "/contact/"
  status = 301

[[redirects]]
  from = "/photogallery/"
  to = "/"
  status = 301
